### PR TITLE
converted server code to TS

### PR DESCRIPTION
**Pull request by DmitryEfimenko**
This is in regards to #2. Next step would be to write something to watch changes to server side code.

Main things changed:
* server side code is now `*.ts`
* moved server code to /src
* wrote appropriate build steps

### CODE REVIEW

**Comment by DmitryEfimenko** [comment]
just noticed, e2e is failing. I'll let you know when it's fixed

**Comment by DmitryEfimenko** [comment]
I see Travis is passing, but actually I'm not sure why. Locally running `npm run tests.all.exp` fails.

Not sure exactly why (the error is weird), but I think it's because it's trying to run `tests.all.exp`, which attempts to span up a web server, which is not needed anymore since I set up Protractor to run tests against actual web server, which I modified as well to work for `dev`.

I think we could now configure travis to run `tests.all`, and everything would be fine.
Let me know what you think

**Comment by vyakymenko** [comment]
It will be good if we will resolve issues with `travis` config. I will remove experimental config.


I think it's a bad idea to overwrite `parent-seed` tasks
 We will create our own dir `express` with tasks for express-seed, like Nathan Walker made in angular-seed-advanced.

**Comment by DmitryEfimenko** [comment]
In the latest commit I mirrored changes from your latest two commits to master.
Travis should be passing now for sure.
It says that branch has conflicts, but I think it's actually all good.
Is there anything else I should do?

**Comment by vyakymenko** [comment]
@DmitryEfimenko , please fix `tools/env/config.ts`, dev.server port must be `9001`

**Comment by DmitryEfimenko** [comment]
that's done

**Comment by vyakymenko** [comment]
@DmitryEfimenko , code look's good. Thank you very much for contributing!
P.S. Today will add `Redis` integration :)

**Pull request merged**
